quoridor: main.c ai.c functions.c ../myallocators/myallocators.o ../myallocators/hash.o
	gcc -o quoridor main.c ai.c functions.c ../myallocators/myallocators.o ../myallocators/hash.o
clean:
	rm quoridor